#index:
#    path: /
#    controller: App\Controller\DefaultController::index
main_url:
  path: /
  controller: App\Controller\MainController::index

main_strona1:
    path:       /
    controller: App\Controller\MainController::show
