#index:
#    path: /
#    controller: App\Controller\DefaultController::index
main_url:
  path: /
  controller: App\Controller\MainController::index

strona1:
  path: home/strona1.html.twig
  controller: App\Controller\MainController::strona1
