#index:
#    path: /
#    controller: App\Controller\DefaultController::index
main_url:
  path: /index
  controller: App\Controller\MainController::index

strona1:
  path: /strona
  controller: App\Controller\MainController::strona1
